#line 2 "radius_dict.c"

#line 4 "radius_dict.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer Radius_create_buffer
#define yy_delete_buffer Radius_delete_buffer
#define yy_flex_debug Radius_flex_debug
#define yy_init_buffer Radius_init_buffer
#define yy_flush_buffer Radius_flush_buffer
#define yy_load_buffer_state Radius_load_buffer_state
#define yy_switch_to_buffer Radius_switch_to_buffer
#define yyin Radiusin
#define yyleng Radiusleng
#define yylex Radiuslex
#define yylineno Radiuslineno
#define yyout Radiusout
#define yyrestart Radiusrestart
#define yytext Radiustext
#define yywrap Radiuswrap
#define yyalloc Radiusalloc
#define yyrealloc Radiusrealloc
#define yyfree Radiusfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Radiusrestart(Radiusin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int Radiusleng;

extern FILE *Radiusin, *Radiusout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Radiustext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Radiustext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Radiusrestart()), so that the user can continue scanning by
	 * just pointing Radiusin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when Radiustext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int Radiusleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow Radiuswrap()'s to do buffer switches
 * instead of setting up a fresh Radiusin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void Radiusrestart (FILE *input_file  );
void Radius_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Radius_create_buffer (FILE *file,int size  );
void Radius_delete_buffer (YY_BUFFER_STATE b  );
void Radius_flush_buffer (YY_BUFFER_STATE b  );
void Radiuspush_buffer_state (YY_BUFFER_STATE new_buffer  );
void Radiuspop_buffer_state (void );

static void Radiusensure_buffer_stack (void );
static void Radius_load_buffer_state (void );
static void Radius_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER Radius_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE Radius_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE Radius_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE Radius_scan_bytes (yyconst char *bytes,int len  );

void *Radiusalloc (yy_size_t  );
void *Radiusrealloc (void *,yy_size_t  );
void Radiusfree (void *  );

#define yy_new_buffer Radius_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Radiusensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Radius_create_buffer(Radiusin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Radiusensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Radius_create_buffer(Radiusin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *Radiusin = (FILE *) 0, *Radiusout = (FILE *) 0;

typedef int yy_state_type;

extern int Radiuslineno;

int Radiuslineno = 1;

extern char *Radiustext;
#define yytext_ptr Radiustext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Radiustext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	Radiusleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[298] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       13,   13,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,   15,   61,   60,   59,    2,
        1,   60,    1,    1,   60,   60,   16,    1,   17,   17,
       28,    1,   29,   29,   47,    1,    1,   47,   47,   47,
       47,    1,   47,   47,   47,   52,   51,    1,   51,   51,
       53,   54,    1,   55,   55,    2,    1,   56,   56,   58,
        2,    1,   60,    2,    1,   60,   12,    1,   13,    2,

        1,   27,   60,   23,   20,   24,   60,   25,   60,   26,
       14,    1,   15,    2,    1,    2,    0,    0,    0,    0,
        0,    0,   16,   17,    0,   28,   29,    0,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   51,   50,   51,   51,   54,   55,    2,   56,
        0,   58,    2,    0,    0,    2,    2,    3,   12,   13,
        2,    0,   21,   22,   14,   15,    2,    0,    0,    0,
        0,    0,    0,   18,   30,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   46,
       50,   51,   51,   57,    2,    0,    0,    0,    0,    0,

        0,    0,   47,   42,   47,   38,   47,   41,   47,   47,
       47,   47,   47,   47,   47,   47,   51,   51,    0,    0,
        0,    0,    0,    0,    6,    0,   47,   47,   40,   47,
       47,   47,   47,   47,   47,   43,   47,   47,   51,   51,
        0,    0,    0,    0,    0,    0,    4,   47,   47,   47,
       34,   47,   47,   37,   33,   44,   32,   51,   51,    0,
        0,    0,    0,    0,   11,    0,   39,   47,   31,   47,
       47,   51,   48,   19,    7,    0,    0,    0,    0,   45,
       35,   47,   50,   48,    5,   10,    0,    0,   47,   49,
        0,    9,   36,   49,    0,    8,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   12,   14,   12,   12,   12,   15,    1,    1,
       16,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   26,   39,   40,   26,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   26,   27,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   26,   62,
       63,   26,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    5,    6,    6,
        6,    6,    6,    6,    1,    7,    6,    6,    6,    6,
        6,    6,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    6,    6,    6,    6,    6,    6,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[332] =
    {   0,
        0,   51,  102,    0,  163,  216,  265,    0,  326,  379,
        0,   10,  432,    0,  495,  548,   22,   35,  601,  654,
      706,  758,   47,   61,  810,  862,  913,  967, 1023, 1076,
     1127, 1178,   74,  100,  124,  147,  186,  198,  239,  251,
      173,  226, 1231, 1284, 1335, 1386,  175, 1630, 1630,    0,
     1630,   12,    4,   18,   37,  251,    0,    0,  278,  309,
        0,    0,  324,  336,    0,   58,   52,   64,   74,   72,
      370,    0,   80,  340,    1, 1630,  158,  157,  109,  135,
     1630,    0,    0,    0,    0,    3,    0,  348,  361,    0,
      170,    0,   93,  169,  170,  358,    0,    0,    0,    0,

        0, 1630,  240, 1630, 1630, 1630,  132, 1630,  169, 1630,
        0,    0,    0,    0,    0,    0,  243,  245,  207,  221,
      273,  272,    0,  495,    0,    0,  517,    0,    0,  255,
      280,  326,  357,  260,  260,  365,  497,  367,  373,  492,
      371,  370,  154,    0,  501,  526,    0,    0,    5,  599,
        0,    0,  152,  491,  527,  499,  540,  529,    0,    0,
        0,  543, 1630, 1630,    0,    0,    0,  499,  558,  564,
      139,  561,  575,    0,    0,  592,  602,  606,  604,  605,
      616,  616,  618,  114,  600,  618,  608,  636,  642,    0,
        0,  657,    0,    0,  642,  647,  649,  643,  648,  652,

      658,  649,  670,    0,  652,    0,  660,    0,  672,  682,
      698,  695,  683,  686,  697,  698,  715,  710,  708,  692,
      720,   93,  707,  718, 1630,  710,  713,   91,    0,  733,
      732,  736,  734,  735,  737,    0,  745,  751,  761,  766,
      744,  772,  747,  760,  749,  767, 1630,  766,  780,  784,
        0,  802,  802,    0,    0,    0,    0,  799,  808,   81,
      805,  796,  806,  821, 1630,  823,    0,  804,    0,  805,
      822,   73,  413, 1630, 1630,  824,  811,  820,  829,    0,
        0,  821,   72, 1630, 1630, 1630,  854,  841,  839,   74,
      853, 1630,    0,    0,  851, 1630, 1630, 1439, 1446, 1453,

     1460, 1467, 1474, 1481, 1488, 1495, 1502, 1509, 1516, 1523,
     1527, 1530, 1533, 1536, 1540, 1546, 1553, 1560, 1567, 1574,
     1581, 1585, 1591, 1598, 1602, 1608, 1615,   59,   44, 1622,
       20
    } ;

static yyconst flex_int16_t yy_def[332] =
    {   0,
      298,  298,  298,    3,  299,  299,    3,    7,  300,  300,
        7,    7,  297,   13,  301,  301,    7,    7,  302,  302,
      303,  303,    7,    7,  304,  304,  305,  305,  306,  306,
      307,  307,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,  308,  308,  309,  309,  297,  297,  297,  310,
      297,  297,  297,  297,  297,  297,  311,  311,  297,  297,
      312,  312,  297,  297,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  297,  314,  314,  314,  314,
      297,  315,  315,  316,  316,  317,  316,  297,  297,  318,
      319,  318,  320,  321,  320,  320,  322,  322,  323,  324,

      323,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      325,  325,  326,  327,  326,  310,  297,  297,  297,  297,
      297,  297,  311,  297,  328,  312,  297,  329,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  314,  330,  314,  314,  315,  316,  317,  297,
      331,  318,  319,  320,  320,  321,  321,  320,  322,  323,
      324,  297,  297,  297,  325,  326,  327,  297,  297,  297,
      297,  297,  297,  328,  329,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      330,  314,  314,  331,  321,  297,  297,  297,  297,  297,

      297,  297,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  314,  314,  297,  297,
      297,  297,  297,  297,  297,  297,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  314,  314,
      297,  297,  297,  297,  297,  297,  297,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  314,  314,  297,
      297,  297,  297,  297,  297,  297,  313,  313,  313,  313,
      313,  314,  314,  297,  297,  297,  297,  297,  297,  313,
      313,  313,  330,  297,  297,  297,  297,  297,  313,  330,
      297,  297,  313,  330,  297,  297,    0,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297
    } ;

static yyconst flex_int16_t yy_nxt[1694] =
    {   0,
      297,  297,   49,   50,  116,  148,  116,  148,   63,   64,
       64,   64,   64,   64,   51,  144,   51,   51,   63,   64,
       64,   64,   64,   64,   81,  194,   51,   51,  142,   51,
       48,   48,   48,   48,   48,   48,  117,   81,  119,  118,
      218,   51,   51,   48,   48,   48,   48,   48,   48,  175,
       51,  142,   51,   49,   50,   88,   89,   89,   89,   89,
       89,  117,  118,  119,  174,   51,  120,   51,   51,   88,
       89,   89,   89,   89,   89,  130,  102,   51,   51,  294,
       51,  290,   48,   48,   48,   48,   48,   48,  283,  120,
      133,  131,   51,   51,  132,  103,  274,  249,  138,  244,

      130,   51,  102,   51,   49,   50,   52,  134,   48,   48,
       48,   48,   48,   48,  131,  133,   51,  132,   53,   54,
      103,  103,   55,  138,  144,  155,  104,  211,   51,   51,
      134,   51,   48,  105,  105,   48,  105,   48,  145,   56,
      163,  163,  163,   53,   54,  200,  103,   55,  155,  104,
      144,  146,   51,  116,   51,   48,  105,  105,   48,  105,
       48,  145,   56,   48,   48,   49,   50,   48,   48,  144,
       48,  116,  144,  144,  297,  110,  146,   51,   48,   58,
       58,   48,   48,   48,   48,   48,   48,  164,  106,   58,
       58,  107,   58,  297,   48,   48,   48,   48,   48,   48,

      106,  157,  155,  107,   58,   58,   48,   48,   48,   48,
       48,   48,  164,   58,  297,   58,   48,   48,   49,   50,
       48,   48,  297,   48,  157,  155,  297,  297,  110,  170,
       51,   48,   58,   58,   48,   48,   48,   48,   48,   48,
      171,  108,   58,   58,  109,   58,  297,   48,   48,   48,
       48,   48,   48,  108,  170,  297,  109,   58,   58,   48,
       48,   48,   48,   48,   48,  171,   58,  121,   58,   48,
      162,  122,  168,   59,   60,   60,   60,   60,   60,  176,
      169,   51,   51,  180,  181,   48,  124,  124,  124,  124,
      124,  124,  121,  162,  297,  168,  122,  297,  297,  297,

      172,  173,   48,  169,  176,  297,   51,   51,  180,  181,
       48,  297,  297,  297,  297,  177,  125,  124,  124,  124,
      124,  124,  124,  172,  173,   48,   48,   48,   49,   50,
       48,   48,  127,  127,  127,  127,  127,  127,  177,  125,
       51,   48,   62,   62,  127,  127,  127,  127,  127,  127,
      297,  297,   62,   62,  178,   62,  150,  150,  150,  150,
      150,  150,  128,  139,  140,  297,  297,   62,   62,  150,
      150,  150,  150,  150,  150,  141,   62,  178,   62,   48,
       48,   49,   50,   48,   48,  128,  151,  158,  139,  140,
      155,  135,  179,   51,   48,   62,   62,  297,  141,  136,

      182,  137,  186,  187,  189,   62,   62,  190,   62,  151,
      158,  297,  297,  155,  297,  179,  135,  297,  284,  297,
       62,   62,  136,  182,  137,  186,  187,  189,  144,   62,
      190,   62,   48,   48,   49,   50,   48,   48,   65,   48,
       65,   65,   65,   65,   65,   65,   51,   48,   66,   67,
       68,   69,   70,   65,   65,   65,   71,   65,   72,   72,
       65,   72,   73,   65,   65,   65,   74,   75,   65,   65,
       65,   65,   65,   66,   67,   68,   69,   70,   65,   65,
       65,   71,   72,   65,   72,   73,   65,   65,   65,   74,
       75,   65,   65,   65,   65,   48,   48,   76,   50,   48,

       48,  297,   48,  124,  124,  124,  124,  124,  124,   51,
       48,   78,   78,  183,  188,   79,  144,  197,   80,  192,
      297,   78,   78,  155,   78,  127,  127,  127,  127,  127,
      127,  157,  297,  297,  184,  185,   78,   78,  183,  188,
       79,  144,  197,   80,  192,   78,  155,   78,   48,   48,
       76,   50,   48,   48,  157,   48,  158,  184,  185,  155,
      193,  155,   51,   48,   78,   78,  297,  297,   79,  195,
      297,   80,  157,  297,   78,   78,  196,   78,  297,  158,
      297,  297,  155,  193,  155,  297,  297,  297,  199,   78,
       78,  198,  195,   79,  202,  157,   80,  201,   78,  196,

       78,   48,   48,   49,   50,   48,   48,  150,  150,  150,
      150,  150,  150,  199,  198,   51,   48,   83,   83,  202,
      201,  203,  204,  205,  206,  207,  297,   83,   83,  212,
       83,  297,  297,  297,  297,  208,  209,  210,  213,  297,
      297,  214,   83,   83,  203,  297,  297,  204,  205,  206,
      207,   83,  212,   83,   48,   48,   49,   50,   48,   48,
      208,  209,  210,  213,  214,  215,  216,  221,   51,   48,
       83,   83,  144,  297,  157,  219,  220,  222,  225,  226,
       83,   83,  228,   83,  297,  297,  227,  223,  215,  224,
      217,  216,  221,  229,  230,   83,   83,  157,  219,  220,

      222,  231,  226,  225,   83,  228,   83,   48,   85,   86,
      223,  227,  224,  217,  232,  234,  229,  237,  235,  230,
       87,  236,   87,   87,  241,  144,  231,  238,  242,  233,
      144,  297,   87,   87,  245,   87,  297,  243,  246,  232,
      234,  235,  237,  247,  236,  240,  248,   87,   87,  241,
      238,  242,  233,  250,  239,  252,   87,  245,   87,   48,
       85,   86,  243,  246,  256,  251,  247,  253,  240,  248,
      254,  255,   87,  257,   87,   87,  144,  239,  250,  260,
      252,  144,  259,  262,   87,   87,  265,   87,  251,  256,
      253,  261,  258,  254,  255,  263,  266,  264,  257,   87,

       87,  297,  260,  297,  268,  267,  262,  259,   87,  265,
       87,   48,   49,   91,  144,  258,  261,  269,  263,  266,
      264,  270,  271,  144,   92,  275,   92,   92,  267,  268,
      273,  276,  297,  277,  272,  280,   92,   92,  281,   92,
      269,  278,  279,  282,  285,  289,  270,  271,  286,  287,
      275,   92,   92,  297,  276,  273,  277,  272,  280,  288,
       92,  281,   92,   48,   49,   91,  278,  279,  282,  285,
      289,  286,  287,  291,  292,  297,   92,  293,   92,   92,
      297,  297,  288,  295,  296,  297,  297,  297,   92,   92,
      297,   92,  297,  297,  297,  297,  297,  292,  291,  297,

      293,  297,  297,   92,   92,  297,  295,  296,  297,  297,
      297,  297,   92,  297,   92,   49,   94,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,   95,  297,   95,
       95,  297,  297,  297,  297,  297,  297,  297,  297,   95,
       95,  297,   95,  297,  297,   96,  297,  297,  297,  297,
      297,  297,  297,  297,   95,   95,  297,  297,  297,  297,
      297,  297,  297,   95,  297,   95,  297,  297,   96,   49,
       94,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,   95,  297,   95,   95,  297,  297,  297,  297,  297,
      297,  297,  297,   95,   95,  297,   95,  297,  297,   96,

      297,  297,  297,  297,  297,  297,  297,  297,   95,   95,
      297,  297,  297,  297,  297,  297,  297,   95,  297,   95,
      297,  297,   96,   48,   48,   49,   50,   48,   48,  297,
       48,  297,  297,  297,  297,  297,  297,   51,   48,   98,
       98,  297,  297,  297,  297,  297,  297,  297,  297,   98,
       98,  297,   98,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,   98,   98,  297,  297,  297,  297,
      297,  297,  297,   98,  297,   98,   48,   48,   49,   50,
       48,   48,  297,   48,  297,  297,  297,  297,  297,  297,
       51,   48,   98,   98,  297,  297,  297,  297,  297,  297,

      297,  297,   98,   98,  297,   98,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,   98,   98,  297,
      297,  297,  297,  297,  297,  297,   98,  297,   98,   49,
      100,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  101,  297,  101,  101,  297,  297,  297,  297,  297,
      297,  297,  297,  101,  101,  297,  101,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  101,  101,
      297,  297,  297,  297,  297,  297,  297,  101,  297,  101,
       49,  100,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  101,  297,  101,  101,  297,  297,  297,  297,

      297,  297,  297,  297,  101,  101,  297,  101,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  101,
      101,  297,  297,  297,  297,  297,  297,  297,  101,  297,
      101,   48,   48,   49,   50,   48,   48,  297,   48,  297,
      297,  297,  297,  297,  297,   51,   48,  112,  112,  297,
      297,  297,  297,  297,  297,  297,  297,  112,  112,  297,
      112,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  112,  112,  297,  297,  297,  297,  297,  297,
      297,  112,  297,  112,   48,   48,   49,   50,   48,   48,
      297,   48,  297,  297,  297,  297,  297,  297,   51,   48,

      112,  112,  297,  297,  297,  297,  297,  297,  297,  297,
      112,  112,  297,  112,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  112,  112,  297,  297,  297,
      297,  297,  297,  297,  112,  297,  112,   49,  114,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  115,
      297,  115,  115,  297,  297,  297,  297,  297,  297,  297,
      297,  115,  115,  297,  115,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  115,  115,  297,  297,
      297,  297,  297,  297,  297,  115,  297,  115,   49,  114,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      115,  297,  115,  115,  297,  297,  297,  297,  297,  297,
      297,  297,  115,  115,  297,  115,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  115,  115,  297,
      297,  297,  297,  297,  297,  297,  115,  297,  115,   48,
       48,   48,   48,   48,   48,   48,   57,   57,   57,   57,
       57,   57,   57,   61,   61,   61,   61,   61,   61,   61,
       77,   77,   77,   77,   77,   77,   77,   82,   82,   82,
       82,   82,   82,   82,   84,   84,   84,   84,   84,   84,
       84,   90,   90,   90,   90,   90,   90,   90,   93,   93,
       93,   93,   93,   93,   93,   97,   97,   97,   97,   97,

       97,   97,   99,   99,   99,   99,   99,   99,   99,  111,
      111,  111,  111,  111,  111,  111,  113,  113,  113,  113,
      113,  113,  113,  116,  116,  297,  116,  116,  116,  116,
      123,  297,  123,  126,  126,  126,  129,  297,  129,  143,
      297,  143,  143,  147,  147,  147,  148,  297,  148,  148,
      148,  148,  148,  149,  149,  149,  149,  149,  149,  149,
      152,  297,  297,  152,  152,  152,  152,  153,  153,  297,
      153,  153,  153,  153,  154,  154,  297,  154,  154,  154,
      154,  156,  156,  297,  156,  156,  156,  156,  159,  297,
      159,  160,  160,  297,  160,  160,  160,  160,  161,  161,

      297,  161,  161,  161,  161,  165,  297,  165,  166,  166,
      297,  166,  166,  166,  166,  167,  167,  297,  167,  167,
      167,  167,  191,  191,  297,  191,  191,  191,  191,   47,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297

    } ;

static yyconst flex_int16_t yy_chk[1694] =
    {   0,
        0,    0,    1,    1,   86,   86,  149,  149,   11,   11,
       11,   11,   11,   11,    1,  193,    1,    1,   12,   12,
       12,   12,   12,   12,   17,  331,    1,    1,   75,    1,
       17,   17,   17,   17,   17,   17,   52,   18,   54,   53,
      193,    1,    1,   18,   18,   18,   18,   18,   18,  329,
        1,   75,    1,    2,    2,   23,   23,   23,   23,   23,
       23,   52,   53,   54,  328,    2,   55,    2,    2,   24,
       24,   24,   24,   24,   24,   66,   33,    2,    2,  290,
        2,  283,   33,   33,   33,   33,   33,   33,  272,   55,
       69,   67,    2,    2,   68,   33,  260,  228,   73,  222,

       66,    2,   34,    2,    3,    3,    3,   70,   34,   34,
       34,   34,   34,   34,   67,   69,    3,   68,    3,    3,
       33,   34,    3,   73,   79,   93,   35,  184,    3,    3,
       70,    3,   35,   35,   35,   35,   35,   35,   79,    3,
      107,  107,  107,    3,    3,  171,   34,    3,   93,   36,
       80,   80,    3,  153,    3,   36,   36,   36,   36,   36,
       36,   79,    3,    5,    5,    5,    5,    5,    5,  143,
        5,   91,   78,   77,   47,   41,   80,    5,    5,    5,
        5,   41,   41,   41,   41,   41,   41,  109,   37,    5,
        5,   37,    5,    0,   37,   37,   37,   37,   37,   37,

       38,   94,   95,   38,    5,    5,   38,   38,   38,   38,
       38,   38,  109,    5,    0,    5,    6,    6,    6,    6,
        6,    6,    0,    6,   94,   95,    0,    0,   42,  119,
        6,    6,    6,    6,   42,   42,   42,   42,   42,   42,
      120,   39,    6,    6,   39,    6,    0,   39,   39,   39,
       39,   39,   39,   40,  119,    0,   40,    6,    6,   40,
       40,   40,   40,   40,   40,  120,    6,   56,    6,    7,
      103,   56,  117,    7,    7,    7,    7,    7,    7,  130,
      118,    7,    7,  134,  135,    7,   59,   59,   59,   59,
       59,   59,   56,  103,    0,  117,   56,    0,    0,    0,

      121,  122,    7,  118,  130,    0,    7,    7,  134,  135,
        7,    0,    0,    0,    0,  131,   59,   60,   60,   60,
       60,   60,   60,  121,  122,    7,    9,    9,    9,    9,
        9,    9,   63,   63,   63,   63,   63,   63,  131,   59,
        9,    9,    9,    9,   64,   64,   64,   64,   64,   64,
        0,    0,    9,    9,  132,    9,   88,   88,   88,   88,
       88,   88,   63,   74,   74,    0,    0,    9,    9,   89,
       89,   89,   89,   89,   89,   74,    9,  132,    9,   10,
       10,   10,   10,   10,   10,   63,   88,   96,   74,   74,
       96,   71,  133,   10,   10,   10,   10,    0,   74,   71,

      136,   71,  138,  139,  141,   10,   10,  142,   10,   88,
       96,    0,    0,   96,    0,  133,   71,    0,  273,    0,
       10,   10,   71,  136,   71,  138,  139,  141,  273,   10,
      142,   10,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   15,   15,   15,   15,   15,

       15,    0,   15,  124,  124,  124,  124,  124,  124,   15,
       15,   15,   15,  137,  140,   15,  145,  168,   15,  145,
        0,   15,   15,  154,   15,  127,  127,  127,  127,  127,
      127,  156,    0,    0,  137,  137,   15,   15,  137,  140,
       15,  146,  168,   15,  145,   15,  154,   15,   16,   16,
       16,   16,   16,   16,  156,   16,  155,  137,  137,  155,
      146,  158,   16,   16,   16,   16,    0,    0,   16,  157,
        0,   16,  157,    0,   16,   16,  162,   16,    0,  155,
        0,    0,  155,  146,  158,    0,    0,    0,  170,   16,
       16,  169,  157,   16,  173,  157,   16,  172,   16,  162,

       16,   19,   19,   19,   19,   19,   19,  150,  150,  150,
      150,  150,  150,  170,  169,   19,   19,   19,   19,  173,
      172,  176,  177,  178,  179,  180,    0,   19,   19,  185,
       19,    0,    0,    0,    0,  181,  182,  183,  186,    0,
        0,  187,   19,   19,  176,    0,    0,  177,  178,  179,
      180,   19,  185,   19,   20,   20,   20,   20,   20,   20,
      181,  182,  183,  186,  187,  188,  189,  198,   20,   20,
       20,   20,  192,    0,  195,  196,  197,  199,  201,  202,
       20,   20,  205,   20,    0,    0,  203,  200,  188,  200,
      192,  189,  198,  207,  209,   20,   20,  195,  196,  197,

      199,  210,  202,  201,   20,  205,   20,   21,   21,   21,
      200,  203,  200,  192,  211,  212,  207,  215,  213,  209,
       21,  214,   21,   21,  219,  218,  210,  216,  220,  211,
      217,    0,   21,   21,  223,   21,    0,  221,  224,  211,
      212,  213,  215,  226,  214,  218,  227,   21,   21,  219,
      216,  220,  211,  230,  217,  232,   21,  223,   21,   22,
       22,   22,  221,  224,  237,  231,  226,  233,  218,  227,
      234,  235,   22,  238,   22,   22,  239,  217,  230,  241,
      232,  240,  240,  243,   22,   22,  245,   22,  231,  237,
      233,  242,  239,  234,  235,  244,  246,  244,  238,   22,

       22,    0,  241,    0,  249,  248,  243,  240,   22,  245,
       22,   25,   25,   25,  258,  239,  242,  250,  244,  246,
      244,  252,  253,  259,   25,  261,   25,   25,  248,  249,
      259,  262,    0,  263,  258,  268,   25,   25,  270,   25,
      250,  264,  266,  271,  276,  282,  252,  253,  277,  278,
      261,   25,   25,    0,  262,  259,  263,  258,  268,  279,
       25,  270,   25,   26,   26,   26,  264,  266,  271,  276,
      282,  277,  278,  287,  288,    0,   26,  289,   26,   26,
        0,    0,  279,  291,  295,    0,    0,    0,   26,   26,
        0,   26,    0,    0,    0,    0,    0,  288,  287,    0,

      289,    0,    0,   26,   26,    0,  291,  295,    0,    0,
        0,    0,   26,    0,   26,   27,   27,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   27,    0,   27,
       27,    0,    0,    0,    0,    0,    0,    0,    0,   27,
       27,    0,   27,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,   27,   27,    0,    0,    0,    0,
        0,    0,    0,   27,    0,   27,    0,    0,   27,   28,
       28,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   28,    0,   28,   28,    0,    0,    0,    0,    0,
        0,    0,    0,   28,   28,    0,   28,    0,    0,   28,

        0,    0,    0,    0,    0,    0,    0,    0,   28,   28,
        0,    0,    0,    0,    0,    0,    0,   28,    0,   28,
        0,    0,   28,   29,   29,   29,   29,   29,   29,    0,
       29,    0,    0,    0,    0,    0,    0,   29,   29,   29,
       29,    0,    0,    0,    0,    0,    0,    0,    0,   29,
       29,    0,   29,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,   29,    0,    0,    0,    0,
        0,    0,    0,   29,    0,   29,   30,   30,   30,   30,
       30,   30,    0,   30,    0,    0,    0,    0,    0,    0,
       30,   30,   30,   30,    0,    0,    0,    0,    0,    0,

        0,    0,   30,   30,    0,   30,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   30,   30,    0,
        0,    0,    0,    0,    0,    0,   30,    0,   30,   31,
       31,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   31,    0,   31,   31,    0,    0,    0,    0,    0,
        0,    0,    0,   31,   31,    0,   31,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   31,   31,
        0,    0,    0,    0,    0,    0,    0,   31,    0,   31,
       32,   32,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   32,    0,   32,   32,    0,    0,    0,    0,

        0,    0,    0,    0,   32,   32,    0,   32,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   32,
       32,    0,    0,    0,    0,    0,    0,    0,   32,    0,
       32,   43,   43,   43,   43,   43,   43,    0,   43,    0,
        0,    0,    0,    0,    0,   43,   43,   43,   43,    0,
        0,    0,    0,    0,    0,    0,    0,   43,   43,    0,
       43,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   43,   43,    0,    0,    0,    0,    0,    0,
        0,   43,    0,   43,   44,   44,   44,   44,   44,   44,
        0,   44,    0,    0,    0,    0,    0,    0,   44,   44,

       44,   44,    0,    0,    0,    0,    0,    0,    0,    0,
       44,   44,    0,   44,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   44,   44,    0,    0,    0,
        0,    0,    0,    0,   44,    0,   44,   45,   45,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   45,
        0,   45,   45,    0,    0,    0,    0,    0,    0,    0,
        0,   45,   45,    0,   45,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   45,   45,    0,    0,
        0,    0,    0,    0,    0,   45,    0,   45,   46,   46,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       46,    0,   46,   46,    0,    0,    0,    0,    0,    0,
        0,    0,   46,   46,    0,   46,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   46,   46,    0,
        0,    0,    0,    0,    0,    0,   46,    0,   46,  298,
      298,  298,  298,  298,  298,  298,  299,  299,  299,  299,
      299,  299,  299,  300,  300,  300,  300,  300,  300,  300,
      301,  301,  301,  301,  301,  301,  301,  302,  302,  302,
      302,  302,  302,  302,  303,  303,  303,  303,  303,  303,
      303,  304,  304,  304,  304,  304,  304,  304,  305,  305,
      305,  305,  305,  305,  305,  306,  306,  306,  306,  306,

      306,  306,  307,  307,  307,  307,  307,  307,  307,  308,
      308,  308,  308,  308,  308,  308,  309,  309,  309,  309,
      309,  309,  309,  310,  310,    0,  310,  310,  310,  310,
      311,    0,  311,  312,  312,  312,  313,    0,  313,  314,
        0,  314,  314,  315,  315,  315,  316,    0,  316,  316,
      316,  316,  316,  317,  317,  317,  317,  317,  317,  317,
      318,    0,    0,  318,  318,  318,  318,  319,  319,    0,
      319,  319,  319,  319,  320,  320,    0,  320,  320,  320,
      320,  321,  321,    0,  321,  321,  321,  321,  322,    0,
      322,  323,  323,    0,  323,  323,  323,  323,  324,  324,

        0,  324,  324,  324,  324,  325,    0,  325,  326,  326,
        0,  326,  326,  326,  326,  327,  327,    0,  327,  327,
      327,  327,  330,  330,    0,  330,  330,  330,  330,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int Radius_flex_debug;
int Radius_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Radiustext;
#line 1 "radius_dict.l"
/*
 * We don't use unput, so don't generate code for it.
 */
/*
 * We don't read from the terminal.
 */
/*
 * The language we're scanning is case-insensitive.
 */
/*
 * Prefix scanner routines with "Radius" rather than "yy", so this scanner
 * can coexist with other scanners.
 */
#line 25 "radius_dict.l"
	/* radius_dict.l
	*
	* RADIUS dictionary parser
	*
	* $Id: radius_dict.l 35983 2011-02-17 18:53:35Z sfisher $
	*
	* Wireshark - Network traffic analyzer
	* By Gerald Combs <gerald@wireshark.org>
	* Copyright 1998 Gerald Combs
	*
	* This program is free software; you can redistribute it and/or
	* modify it under the terms of the GNU General Public License
	* as published by the Free Software Foundation; either version 2
	* of the License, or (at your option) any later version.
	*
	* This program is distributed in the hope that it will be useful,
	* but WITHOUT ANY WARRANTY; without even the implied warranty of
	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	* GNU General Public License for more details.
	*
	* You should have received a copy of the GNU General Public License
	* along with this program; if not, write to the Free Software
	* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
	*/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <epan/packet.h>
#include <epan/dissectors/packet-radius.h>
#include "radius_dict_lex.h"
#include <wsutil/file_util.h>

#ifdef _WIN32
/* disable Windows VC compiler warning "signed/unsigned mismatch" associated  */
/* with YY_INPUT code generated by flex versions such as 2.5.35.              */
#pragma warning (disable:4018)
#endif

#define ECHO
#define MAX_INCLUDE_DEPTH 10

	void add_vendor(const gchar* name, guint32 vendor_id, guint vendor_type_octets, guint vendor_length_octets, gboolean vendor_has_flags);
	void add_value(const gchar* attrib_name,const  gchar* value_repr, long value);
	void add_tlv(const gchar* name, const  gchar* code, radius_attr_dissector_t type, const gchar* current_attr);
	void add_attribute(const gchar*,const  gchar*, radius_attr_dissector_t,const  gchar*, gboolean, gboolean, const gchar*);

	static YY_BUFFER_STATE include_stack[10];
	static int include_stack_ptr = 0;

	static radius_dictionary_t* dict = NULL;
	static GHashTable* value_strings = NULL; /* GArray(value_string) by attribute name */

	static gchar* attr_name = NULL;
	static gchar* attr_id = NULL;
	static radius_attr_dissector_t* attr_type = NULL;
	static gchar* attr_vendor = NULL;
	static gchar* vendor_name = NULL;
	static guint32 vendor_id = 0;
	static guint vendor_type_octets = 1;
	static guint vendor_length_octets = 1;
	static gboolean vendor_has_flags = FALSE;
	static gchar* value_repr = NULL;
	static gboolean encrypted = FALSE;
	static gboolean has_tag = FALSE;
	static gchar* current_vendor = NULL;
	static gchar* current_attr = NULL;

	static GString* error = NULL;
	static gchar* directory = NULL;
	static int linenums[] = {1,1,1,1,1,1,1,1,1,1};
	static gchar* fullpaths[] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};


#line 1054 "radius_dict.c"

#define INITIAL 0
#define WS_OUT 1
#define VENDOR 2
#define VENDOR_W_NAME 3
#define ATTR 4
#define ATTR_W_NAME 5
#define ATTR_W_ID 6
#define ATTR_W_TYPE 7
#define ATTR_W_VENDOR 8
#define VALUE 9
#define VALUE_W_ATTR 10
#define VALUE_W_NAME 11
#define INCLUDE 12
#define JUNK 13
#define BEGIN_VENDOR 14
#define END_VENDOR 15
#define VENDOR_W_ID 16
#define VENDOR_W_FORMAT 17
#define VENDOR_W_TYPE_OCTETS 18
#define VENDOR_W_LENGTH_OCTETS 19
#define VENDOR_W_CONTINUATION 20
#define BEGIN_TLV 21
#define END_TLV 22

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Radiuslex_destroy (void );

int Radiusget_debug (void );

void Radiusset_debug (int debug_flag  );

YY_EXTRA_TYPE Radiusget_extra (void );

void Radiusset_extra (YY_EXTRA_TYPE user_defined  );

FILE *Radiusget_in (void );

void Radiusset_in  (FILE * in_str  );

FILE *Radiusget_out (void );

void Radiusset_out  (FILE * out_str  );

int Radiusget_leng (void );

char *Radiusget_text (void );

int Radiusget_lineno (void );

void Radiusset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Radiuswrap (void );
#else
extern int Radiuswrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Radiustext, Radiusleng, 1, Radiusout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Radiusin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Radiusin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, Radiusin))==0 && ferror(Radiusin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Radiusin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Radiuslex (void);

#define YY_DECL int Radiuslex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Radiustext and Radiusleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 107 "radius_dict.l"

#line 1263 "radius_dict.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! Radiusin )
			Radiusin = stdin;

		if ( ! Radiusout )
			Radiusout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Radiusensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Radius_create_buffer(Radiusin,YY_BUF_SIZE );
		}

		Radius_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of Radiustext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 297 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "radius_dict.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 "radius_dict.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 "radius_dict.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 113 "radius_dict.l"
{ BEGIN VENDOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 114 "radius_dict.l"
{ BEGIN ATTR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "radius_dict.l"
{ BEGIN VALUE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "radius_dict.l"
{ BEGIN INCLUDE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 117 "radius_dict.l"
{ BEGIN BEGIN_VENDOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 118 "radius_dict.l"
{ BEGIN END_VENDOR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 119 "radius_dict.l"
{ BEGIN BEGIN_TLV; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 120 "radius_dict.l"
{ BEGIN END_TLV; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 122 "radius_dict.l"
{
    if (current_vendor) {
        g_free(current_vendor);
    }
    current_vendor = g_strdup(Radiustext);
    BEGIN WS_OUT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 129 "radius_dict.l"
{
    if (current_vendor) {
        g_free(current_vendor);
        current_vendor = NULL;
    }
    BEGIN WS_OUT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 137 "radius_dict.l"
{
    if (current_attr) {
        g_free(current_attr);
    }
    current_attr = g_strdup(Radiustext);
    BEGIN WS_OUT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 144 "radius_dict.l"
{
    if (current_attr) {
        g_free(current_attr);
        current_attr = NULL;
    }
    BEGIN WS_OUT;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 152 "radius_dict.l"
{
    vendor_name = g_strdup(Radiustext);
    vendor_type_octets = 1;
    vendor_length_octets = 1;
    vendor_has_flags = FALSE;
    BEGIN VENDOR_W_NAME;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "radius_dict.l"
{
    vendor_id = strtol(Radiustext,NULL,10);
    BEGIN VENDOR_W_ID;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "radius_dict.l"
{
    vendor_id = strtol(Radiustext,NULL,16);
    BEGIN VENDOR_W_ID;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "radius_dict.l"
{
    BEGIN VENDOR_W_FORMAT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 170 "radius_dict.l"
{
    vendor_type_octets = strtol(Radiustext,NULL,10);
    BEGIN VENDOR_W_TYPE_OCTETS;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 174 "radius_dict.l"
{
    vendor_length_octets = strtol(Radiustext+1,NULL,10);
    BEGIN VENDOR_W_LENGTH_OCTETS;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 178 "radius_dict.l"
{
    vendor_has_flags = TRUE;
    BEGIN VENDOR_W_CONTINUATION;
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
#line 183 "radius_dict.l"
case 24:
/* rule 24 can match eol */
#line 184 "radius_dict.l"
case 25:
/* rule 25 can match eol */
#line 185 "radius_dict.l"
case 26:
/* rule 26 can match eol */
#line 186 "radius_dict.l"
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 186 "radius_dict.l"
{
    add_vendor(vendor_name, vendor_id, vendor_type_octets, vendor_length_octets, vendor_has_flags);
    g_free(vendor_name);
    BEGIN WS_OUT;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 192 "radius_dict.l"
{ attr_name = g_strdup(Radiustext); encrypted = FALSE; has_tag = FALSE; BEGIN ATTR_W_NAME; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 193 "radius_dict.l"
{ attr_id = g_strdup(Radiustext);  BEGIN ATTR_W_ID;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 194 "radius_dict.l"
{ attr_id = g_strdup_printf("%u",(int)strtoul(Radiustext,NULL,16)); BEGIN ATTR_W_ID;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 195 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 196 "radius_dict.l"
{ attr_type = radius_string;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 197 "radius_dict.l"
{ attr_type = radius_octets;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 198 "radius_dict.l"
{ attr_type = radius_ipaddr;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 199 "radius_dict.l"
{ attr_type = radius_ipv6addr;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 200 "radius_dict.l"
{ attr_type = radius_ipv6prefix;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 201 "radius_dict.l"
{ attr_type = radius_ipxnet;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 202 "radius_dict.l"
{ attr_type = radius_date;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 203 "radius_dict.l"
{ attr_type = radius_abinary;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 204 "radius_dict.l"
{ attr_type = radius_ether;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 205 "radius_dict.l"
{ attr_type = radius_ifid;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 206 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 207 "radius_dict.l"
{ attr_type = radius_integer;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 208 "radius_dict.l"
{ attr_type = radius_signed;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 209 "radius_dict.l"
{ attr_type = radius_combo_ip;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 210 "radius_dict.l"
{ attr_type = radius_tlv;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 211 "radius_dict.l"
{ attr_type = radius_octets;  BEGIN ATTR_W_TYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 212 "radius_dict.l"
{ has_tag = TRUE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 213 "radius_dict.l"
{ encrypted=TRUE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 214 "radius_dict.l"
;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 215 "radius_dict.l"
{
    attr_vendor = g_strdup(Radiustext);
    add_attribute(attr_name,attr_id,attr_type,attr_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_vendor);
    g_free(attr_name);
    attr_id = NULL;
    attr_vendor = NULL;
    attr_name = NULL;
    BEGIN WS_OUT;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 226 "radius_dict.l"
{
    add_attribute(attr_name,attr_id,attr_type,current_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_name);
    linenums[include_stack_ptr]++;
    has_tag = FALSE;
    encrypted=FALSE;
    BEGIN WS_OUT;
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 235 "radius_dict.l"
{
    add_attribute(attr_name,attr_id,attr_type,attr_vendor,encrypted,has_tag,current_attr);
    g_free(attr_id);
    g_free(attr_vendor);
    g_free(attr_name);
    linenums[include_stack_ptr]++;
    BEGIN WS_OUT;
};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 244 "radius_dict.l"
{ attr_name = g_strdup(Radiustext); BEGIN VALUE_W_ATTR; }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 245 "radius_dict.l"
{ value_repr = g_strdup(Radiustext); BEGIN VALUE_W_NAME; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 246 "radius_dict.l"
{ add_value(attr_name,value_repr,strtol(Radiustext,NULL,10));  g_free(attr_name); g_free(value_repr); BEGIN WS_OUT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 247 "radius_dict.l"
{ add_value(attr_name,value_repr,strtol(Radiustext,NULL,16));  g_free(attr_name); g_free(value_repr); BEGIN WS_OUT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "radius_dict.l"
{
	if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ) {
		g_string_append_printf(error, "$INCLUDE files nested to deeply\n");
		yyterminate();
	}

	include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;

	fullpaths[include_stack_ptr] = g_strdup_printf("%s" G_DIR_SEPARATOR_S "%s",
	    directory,Radiustext);

	Radiusin = ws_fopen( fullpaths[include_stack_ptr], "r" );

	if (!Radiusin) {
		if (errno) {
			g_string_append_printf(error, "Could not open file: '%s', error: %s\n", fullpaths[include_stack_ptr], strerror(errno) );
			yyterminate();
		}
	} else {
		linenums[include_stack_ptr] = 1;
		Radius_switch_to_buffer(Radius_create_buffer(Radiusin,YY_BUF_SIZE ) );
	}


	BEGIN WS_OUT;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(WS_OUT):
case YY_STATE_EOF(VENDOR):
case YY_STATE_EOF(VENDOR_W_NAME):
case YY_STATE_EOF(ATTR):
case YY_STATE_EOF(ATTR_W_NAME):
case YY_STATE_EOF(ATTR_W_ID):
case YY_STATE_EOF(ATTR_W_TYPE):
case YY_STATE_EOF(ATTR_W_VENDOR):
case YY_STATE_EOF(VALUE):
case YY_STATE_EOF(VALUE_W_ATTR):
case YY_STATE_EOF(VALUE_W_NAME):
case YY_STATE_EOF(INCLUDE):
case YY_STATE_EOF(JUNK):
case YY_STATE_EOF(BEGIN_VENDOR):
case YY_STATE_EOF(END_VENDOR):
case YY_STATE_EOF(VENDOR_W_ID):
case YY_STATE_EOF(VENDOR_W_FORMAT):
case YY_STATE_EOF(VENDOR_W_TYPE_OCTETS):
case YY_STATE_EOF(VENDOR_W_LENGTH_OCTETS):
case YY_STATE_EOF(VENDOR_W_CONTINUATION):
case YY_STATE_EOF(BEGIN_TLV):
case YY_STATE_EOF(END_TLV):
#line 276 "radius_dict.l"
{

	fclose(Radiusin);
	Radiusin = NULL;

	if ( --include_stack_ptr < 0 ) {
		yyterminate();
	} else {
		g_free(fullpaths[include_stack_ptr+1]);
		fullpaths[include_stack_ptr+1] = NULL;

		Radius_delete_buffer(YY_CURRENT_BUFFER );
		Radius_switch_to_buffer(include_stack[include_stack_ptr]);
	}

	BEGIN WS_OUT;
}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 294 "radius_dict.l"
{ linenums[include_stack_ptr]++; BEGIN WS_OUT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 297 "radius_dict.l"
ECHO;
	YY_BREAK
#line 1782 "radius_dict.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Radiusin at a new source and called
			 * Radiuslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = Radiusin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( Radiuswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * Radiustext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of Radiuslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Radiusrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Radiusrestart(Radiusin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) Radiusrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Radiusrestart(Radiusin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Radiuswrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve Radiustext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Radiusrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Radiusensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Radius_create_buffer(Radiusin,YY_BUF_SIZE );
	}

	Radius_init_buffer(YY_CURRENT_BUFFER,input_file );
	Radius_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Radius_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Radiuspop_buffer_state();
	 *		Radiuspush_buffer_state(new_buffer);
     */
	Radiusensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Radius_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (Radiuswrap()) processing, but the only time this flag
	 * is looked at is after Radiuswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void Radius_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	Radiusin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Radius_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Radiusalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) Radiusalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_create_buffer()" );

	b->yy_is_our_buffer = 1;

	Radius_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Radius_create_buffer()
 * 
 */
    void Radius_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		Radiusfree((void *) b->yy_ch_buf  );

	Radiusfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Radiusrestart() or at EOF.
 */
    static void Radius_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Radius_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then Radius_init_buffer was _probably_
     * called from Radiusrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Radius_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Radius_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Radiuspush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Radiusensure_buffer_stack();

	/* This block is copied from Radius_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Radius_switch_to_buffer. */
	Radius_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Radiuspop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Radius_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Radius_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Radiusensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)Radiusalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Radiusensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)Radiusrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Radiusensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE Radius_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) Radiusalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	Radius_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Radiuslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Radius_scan_bytes() instead.
 */
YY_BUFFER_STATE Radius_scan_string (yyconst char * yystr )
{
    
	return Radius_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Radiuslex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Radius_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) Radiusalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Radius_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Radius_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Radius_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Radiustext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		Radiustext[Radiusleng] = (yy_hold_char); \
		(yy_c_buf_p) = Radiustext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		Radiusleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Radiusget_lineno  (void)
{
        
    return Radiuslineno;
}

/** Get the input stream.
 * 
 */
FILE *Radiusget_in  (void)
{
        return Radiusin;
}

/** Get the output stream.
 * 
 */
FILE *Radiusget_out  (void)
{
        return Radiusout;
}

/** Get the length of the current token.
 * 
 */
int Radiusget_leng  (void)
{
        return Radiusleng;
}

/** Get the current token.
 * 
 */

char *Radiusget_text  (void)
{
        return Radiustext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void Radiusset_lineno (int  line_number )
{
    
    Radiuslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see Radius_switch_to_buffer
 */
void Radiusset_in (FILE *  in_str )
{
        Radiusin = in_str ;
}

void Radiusset_out (FILE *  out_str )
{
        Radiusout = out_str ;
}

int Radiusget_debug  (void)
{
        return Radius_flex_debug;
}

void Radiusset_debug (int  bdebug )
{
        Radius_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Radiuslex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Radiusin = stdin;
    Radiusout = stdout;
#else
    Radiusin = (FILE *) 0;
    Radiusout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Radiuslex_init()
     */
    return 0;
}

/* Radiuslex_destroy is for both reentrant and non-reentrant scanners. */
int Radiuslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Radius_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Radiuspop_buffer_state();
	}

	/* Destroy the stack itself. */
	Radiusfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Radiuslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Radiusalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *Radiusrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void Radiusfree (void * ptr )
{
	free( (char *) ptr );	/* see Radiusrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 297 "radius_dict.l"



void add_vendor(const gchar* name, guint32 vendor_id, guint vendor_type_octets, guint vendor_length_octets, gboolean vendor_has_flags) {
	radius_vendor_info_t* v;

	v = g_hash_table_lookup(dict->vendors_by_id, GUINT_TO_POINTER(vendor_id));

	if (!v) {
		v = g_malloc(sizeof(radius_vendor_info_t));
		v->attrs_by_id = g_hash_table_new(g_direct_hash,g_direct_equal);
		v->code = vendor_id;
		v->ett = -1;
		v->name = NULL;
	}
        /* Assume that the dictionary knows the 'ground truth' about the 
         * type/length/has_flags information and thus allow the dictionary to
         * overwrite these values even for vendors that have already been loaded.
         */
	v->type_octets = vendor_type_octets;
	v->length_octets = vendor_length_octets;
	v->has_flags = vendor_has_flags; 

	if (v->name)
		g_free((gpointer) v->name);
	v->name = g_strdup(name);

	g_hash_table_insert(dict->vendors_by_id,GUINT_TO_POINTER(v->code),v);
	g_hash_table_insert(dict->vendors_by_name, (gpointer) v->name, v);
}

void add_attribute(const gchar* name, const  gchar* codestr, radius_attr_dissector_t type, const  gchar* vendor_name, gboolean crypt, gboolean tagged, const gchar* current_attr) {
	radius_attr_info_t* a;
	GHashTable* by_id;
	guint32 code;


	if (current_attr){
		add_tlv(name, codestr, type, current_attr);
		return;
	}


	if (vendor_name) {
		radius_vendor_info_t* v;
		v = g_hash_table_lookup(dict->vendors_by_name,vendor_name);

		if (! v) {
			g_string_append_printf(error, "Vendor: '%s', does not exist in %s:%i \n", vendor_name, fullpaths[include_stack_ptr], linenums[include_stack_ptr] );
			BEGIN JUNK;
			return;
		} else {
			by_id = v->attrs_by_id;
		}
	} else {
		by_id = dict->attrs_by_id;
	}

	code=strtol(codestr, NULL, 10);

	a=g_hash_table_lookup(by_id, GUINT_TO_POINTER(code));

	if (!a) {
		a = g_malloc(sizeof(radius_attr_info_t));
		a->name = NULL;
		a->dissector = NULL;
	}

	a->code = code;
	a->encrypt = crypt;
	a->tagged =  tagged;
	a->type = type;
	a->vs = NULL;
	a->hf = -1;
	a->hf64 = -1;
	a->hf_tag = -1;
	a->hf_len = -1;
	a->ett = -1;
	a->tlvs_by_id = NULL;

	if (a->name)
		g_free((gpointer) a->name);
	a->name = g_strdup(name);

	g_hash_table_insert(by_id, GUINT_TO_POINTER(code),a);
	g_hash_table_insert(dict->attrs_by_name,(gpointer) (a->name),a);
}

void add_tlv(const gchar* name, const  gchar* codestr, radius_attr_dissector_t type, const gchar* current_attr) {
	radius_attr_info_t* a;
	radius_attr_info_t* s;
	guint32 code;

	a = g_hash_table_lookup(dict->attrs_by_name, current_attr);

	if (! a) {
		g_string_sprintfa(error, "Attr: '%s', does not exist in %s:%i \n", current_attr, fullpaths[include_stack_ptr], linenums[include_stack_ptr]);
		BEGIN JUNK;
		return;
	}

	if (type == radius_tlv) {
		g_string_sprintfa(error, "sub-TLV: '%s', sub-TLV's type is specified as tlv in %s:%i \n", name, fullpaths[include_stack_ptr], linenums[include_stack_ptr]);
		BEGIN JUNK;
		return;
	}


	if (! a->tlvs_by_id) {
		a->tlvs_by_id = g_hash_table_new(g_direct_hash,g_direct_equal);
	}

	code=strtol(codestr, NULL, 10);
		
	s = g_hash_table_lookup(a->tlvs_by_id, GUINT_TO_POINTER(code));

	if (!s) {
		s = g_malloc(sizeof(radius_attr_info_t));
		s->name = NULL;
		s->dissector = NULL;
	}

	s->code = code;
	s->type = type;
	s->encrypt = FALSE;
	s->tagged = FALSE;
	s->dissector = NULL;
	s->vs = NULL;
	s->hf = -1;
	s->hf64 = -1;
	s->hf_tag = -1;
	s->hf_len = -1;
	s->ett = -1;
	s->tlvs_by_id = NULL;

	if (s->name)
		g_free((gpointer) s->name);
	s->name = g_strdup(name);

	g_hash_table_insert(a->tlvs_by_id,GUINT_TO_POINTER(s->code),s);
	g_hash_table_insert(dict->tlvs_by_name,(gpointer) (s->name),s);
}

void add_value(const gchar* attrib_name, const gchar* value_repr, long value) {
	value_string v;
	GArray* a = g_hash_table_lookup(value_strings,attrib_name);

	if (! a) {
		a = g_array_new(TRUE,TRUE,sizeof(value_string));
		g_hash_table_insert(value_strings,g_strdup(attrib_name),a);
	}

	v.value = value;
	v.strptr = g_strdup(value_repr);

	g_array_append_val(a,v);
}

static void setup_tlvs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* s = v;
	gpointer key;

	union {
		GArray* a;
		gpointer p;
	} vs;

	if (g_hash_table_lookup_extended(value_strings, s->name, &key, &vs.p)) {
		s->vs = (value_string*) vs.a->data;
		g_array_free(vs.a, FALSE);
		g_hash_table_remove(value_strings, key);
		g_free(key);
	}
}

static void setup_attrs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* a = v;
	gpointer key;

	union {
		GArray* a;
		gpointer p;
	} vs;

	if (g_hash_table_lookup_extended(value_strings,a->name,&key,&vs.p) ) {
		a->vs = (value_string*) vs.a->data;
		g_array_free(vs.a,FALSE);
		g_hash_table_remove(value_strings,key);
		g_free(key);
	}

	if (a->tlvs_by_id) {
		g_hash_table_foreach(a->tlvs_by_id, setup_tlvs, p);
	}
}

static void setup_vendors(gpointer k _U_, gpointer v, gpointer p) {
	radius_vendor_info_t* vnd = v;

	g_hash_table_foreach(vnd->attrs_by_id,setup_attrs,p);
}

static gboolean destroy_value_strings(gpointer k, gpointer v, gpointer p _U_) {
    value_string* vs = (value_string*)(((GArray*)v)->data);

	g_free(k);

    for (;vs->strptr;vs++) {
        g_free((void*)vs->strptr);
    }

	g_array_free(v,TRUE);
	return TRUE;
}

static gboolean destroy_tlvs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* s = v;
	int i;

	g_free((gpointer) (s->name));

	if (s->vs) {
		for(i=0; s->vs[i].strptr; i++) {
			g_free((void *)s->vs[i].strptr);
		}
		g_free((void *)s->vs);
	}
	g_free(s);
	return TRUE;
}

static gboolean destroy_attrs(gpointer k _U_, gpointer v, gpointer p _U_) {
	radius_attr_info_t* a = v;
	int i;

	g_free((gpointer) (a->name));
	if (a->tlvs_by_id) {
		g_hash_table_foreach_remove(a->tlvs_by_id, destroy_tlvs, p);
		g_hash_table_destroy(a->tlvs_by_id);
	}

	if (a->vs) {
		for(i=0; a->vs[i].strptr; i++) {
			g_free((void *)a->vs[i].strptr);
		}
		g_free((void *)a->vs);
	}
	g_free(a);
	return TRUE;
}

static gboolean destroy_vendors(gpointer k _U_, gpointer v, gpointer p) {
	radius_vendor_info_t* vnd = v;
	g_free( (gpointer) vnd->name);
	g_hash_table_foreach_remove(vnd->attrs_by_id,destroy_attrs,p);
	g_hash_table_destroy(vnd->attrs_by_id);
	g_free(vnd);
	return TRUE;
}

static void destroy_dict(radius_dictionary_t* d) {
	g_hash_table_foreach_remove(d->attrs_by_id,destroy_attrs,NULL);
	g_hash_table_foreach_remove(d->vendors_by_id,destroy_vendors,NULL);
	g_hash_table_destroy(d->vendors_by_id);
	g_hash_table_destroy(d->attrs_by_id);
	g_hash_table_destroy(d->vendors_by_name);
	g_hash_table_destroy(d->attrs_by_name);
	g_free(d);
}

gboolean radius_load_dictionary (radius_dictionary_t* d, gchar* dir, const gchar* filename, gchar** err_str) {
	int i;

	dict = d;
	directory = dir;

	fullpaths[include_stack_ptr] = g_strdup_printf("%s" G_DIR_SEPARATOR_S "%s",
	    directory,filename);

	error = g_string_new("");

	Radiusin = ws_fopen(fullpaths[include_stack_ptr],"r");

	if (!Radiusin) {
		g_string_append_printf(error, "Could not open file: '%s', error: %s\n", fullpaths[include_stack_ptr], strerror(errno) );
		g_free(fullpaths[include_stack_ptr]);
		*err_str = error->str;
		g_string_free(error,FALSE);
		return FALSE;
	}

	value_strings = g_hash_table_new(g_str_hash,g_str_equal);

	BEGIN WS_OUT;

	Radiuslex();

	if (Radiusin != NULL) fclose(Radiusin);
	Radiusin = NULL;

	for (i=0; i < 10; i++) {
		if (fullpaths[i]) g_free(fullpaths[i]);
	}

	g_hash_table_foreach(dict->attrs_by_id,setup_attrs,NULL);
	g_hash_table_foreach(dict->vendors_by_id,setup_vendors,NULL);
	g_hash_table_foreach_remove(value_strings,destroy_value_strings,NULL);

	if (error->len > 0) {
		 *err_str = error->str;
		g_string_free(error,FALSE);
		destroy_dict(dict);
		return FALSE;
	} else {
		*err_str = NULL;
		g_string_free(error,TRUE);
		return TRUE;
	}
}

/*
 * We want to stop processing when we get to the end of the input.
 * (%option noyywrap is not used because if used then
 * some flex versions (eg: 2.5.35) generate code which causes
 * warnings by the Windows VC compiler).
 */

int Radiuswrap(void) {
    return 1;
}

